config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :addresses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "addresses#new"
  get "forecasts/:zip", to: "forecasts#show", as: "forecast"

  mount Auth::Engine, at: "/auth"
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  validates :street, presence: true
  validates :zip, presence: true
  validates :zip, presence: true, format: /\A\d{5}(-\d{4})?\z/
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
# frozen_string_literal: true

class Forecast < ApplicationRecord
  belongs_to :address

  delegate :city, :zip, to: :address

  def cached?
    Rails.cache.exist?(cache_key)
  end

  def cache_key
    "forecasts/#{zip}"
  end

  def temperature_current
    response["temperature_current"]
  end

  def temperature_high
    response["temperature_high"]
  end

  def temperature_low
    response["temperature_low"]
  end

  # @return [Array[Hash]]
  def forecasts
    @forecasts ||= response["forecast"].any? ? response["forecast"] : []
  end
end

app/controllers/addresses_controller.rb
# frozen_string_literal: true

class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to(forecast_url(@address.zip, street: @address.street)) }
        format.json { render(:show, status: :created, location: @address) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @address.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to(address_url(@address), notice: "Address was successfully updated.") }
        format.json { render(:show, status: :ok, location: @address) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @address.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy!

    respond_to do |format|
      format.html { redirect_to(addresses_url, notice: "Address was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = Address.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def address_params
    params.require(:address).permit(:street, :zip)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
# frozen_string_literal: true

class ForecastsController < ApplicationController
  def show
    @in_cache = cached?

    @forecast = Rails.cache.fetch("forecasts/#{forecast_params[:zip]}", expires_in: 30.minutes) do
      addr = Address.find_or_create_by(forecast_params)
      result = WeatherForecaster.new(address: addr).call
      if result.success?
        forecast = Forecast.find_or_create_by(address: addr)
        forecast.response = result.success
        forecast.save
        forecast
      else
        flash[:error] = "Error getting forecast for zip #{forecast_params[:zip]}"
        Rails.logger.error(result.failure)
        nil
      end
    end
  end

  # Only allow a list of trusted parameters through.
  private def forecast_params
    params.permit(:zip, :street)
  end

  private def cached?
    Rails.cache.exist?("forecasts/#{forecast_params[:zip]}")
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p class="my-5">
    <strong class="font-medium mb-1">Street:</strong>
    <%= address.street %>
  </p>

  <p class="my-5">
    <strong class="font-medium mb-1">Zip:</strong>
    <%= address.zip %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this address", address, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this address', edit_address_path(address), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <p>Path: <%= forecast_path(address.zip, street: address.street) %></p>
    <%= link_to "Forecast", forecast_path(address.zip, street: address.street), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address, class: "contents") do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :street %>
    <%= form.text_field :street, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :zip %>
    <%= form.text_field :zip, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Get Forecast", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing address</h1>

  <%= render "form", address: @address %>

  <%= link_to "Show this address", @address, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to addresses", addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/addresses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Addresses</h1>
    <%= link_to 'New address', new_address_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="addresses" class="min-w-full">
    <%= render @addresses %>
  </div>
</div>

app/views/addresses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Weather Forecast</h1>

  <%= render "form", address: @address %>
</div>

app/views/addresses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @address %>

    <%= link_to 'Edit this address', edit_address_path(@address), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this address', address_path(@address), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to addresses', addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/forecasts/_form.html.erb
<%= form_with url: "/forecasts" do |form| %>
  <label class="block mb-6">
    <span class="text-gray-700">Street Address</span>
    <input
      name="street"
      type="text"
      class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
      value="9603 Custer Rd"
    />
  </label>

  <label class="block mb-6">
    <span class="text-gray-700">Zip</span>
    <input
      name="zip"
      type="text"
      inputmode="numeric"
      pattern="\d{5}"
      class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
      value="75025"
    />
  </label>
  <%= form.submit %>
<% end %>

app/views/forecasts/create.html.erb
<p>In create.html.erb</p>
<p><%= @forecast %></p>

app/views/forecasts/index.html.erb
<h1 class="font-bold text-4xl">Forecasts#index</h1>

<%= render "form", address: @address %>

app/views/forecasts/show.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<% if @forecast %>
  <div class="rounded-lg p-4 text-white bg-gradient-to-b from-blue-500 to-blue-300 mb-10">
    <div class="flow-root">   
      <div class="float-left">
        <p class="tx-sm"><%= @forecast.city %> (<%= @forecast.zip %>)</p>
        <p class="text-4xl"><%= @forecast.temperature_current %>&deg;</p>
      </div>
      <div class="float-right">
        <p class="tx-sm">H:<%=@forecast.temperature_low %>&deg; L:<%= @forecast.temperature_high %>&deg;</p>
        <p class="tx-sm">
          <% if @in_cache %>
            cached
          <% else %>
            not cached
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <h1 class="inline-block text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">Forecast</h1>

  <% @forecast.forecasts.each do |f| %>
    <div class="bg-gray-100 rounded-lg border-2 border-black p-4 w-full shadow-lg text-black mb-5">
      <div class="grid grid-flow-col gap-3">
        <div class="col-span-1">
          <img src="<%= f["icon"] %>">
        </div>
        <div class="col-span-3">
          <div class="text-2xl"><%= f["name"] %></div>
          <div class=""><%= f["detailedForecast"] %></div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <h1 class="inline-block text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">No Forecast...</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mt-28 mx-auto flex">
      <div class="basis-1/4"></div>
      <div class="basis-1/2">
        <%= yield %>
      </div>
      <div class="basis-1/4"></div>
    </main>
  </body>
</html>